{
 "title": "Opencell V11",
 "description": "Containers metrics for Opencell",
 "tags": [
  "Prometheus",
  "Docker",
  "Opencell"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "templating": {
  "list": [
   { "name": "scrap_time", "query": "5m" },
   { "name": "job", "label": "job", "query": "perf.opencell.work" },
   {
    "name": "link",
    "query": "https://matooma.oc-saas.eu/opencell/pages/admin/job/jobInstanceDetail.jsf?"
   }
  ]
 },
 "panels": [
  { "title": "Systeme  - Instant", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load - Opencell",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{job=\"$job\",container_label_com_docker_compose_service=\"opencell\"}[5m])) / count(node_cpu_seconds_total{job=\"$job\",mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Load by job",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{job=\"$job\"}) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes{job=\"$job\"}) ) / sum(node_memory_MemTotal_bytes{job=\"$job\"}) * 100"
    }
   ]
  },
  {
   "title": "Job Status",
   "type": "graph",
   "description": "Status of Jobs",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"application_is_running_.*\",job=\"$job\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\",container_label_org_label_schema_group=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Disk IOps Completed（IOPS）",
   "type": "graph",
   "description": "Read/write completions per secon",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{job=~\"$job\"}[1m])",
     "legendFormat": "{{device}}_Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{job=~\"$job\"}[1m])",
     "legendFormat": "{{device}}_Writes completed"
    }
   ]
  },
  { "title": "Opencell Jobs Informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "graph",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s", "label": "Time read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{job=~\"$job\"}[2m]) / rate(node_disk_reads_completed_total{job=~\"$job\"}[2m])",
     "legendFormat": "{{device}}_Read time"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{job=~\"$job\"}[2m]) / rate(node_disk_writes_completed_total{job=~\"$job\"}[2m])",
     "legendFormat": "{{device}}_Write time"
    }
   ]
  },
  {
   "title": "I/O Usage by Job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{job=\"$job\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{job=\"$job\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total{customer=\"$customer\"}[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Current CPU Core Utilization by job",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(avg by () (sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{job=\"$job\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": "Avg"
    },
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max((sum by (cpu) ( (clamp_max(irate(node_cpu_seconds_total{job=\"$job\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "____________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 55 },
   "targets": [
    { "metric": "machine_cpu_cores" }
   ]
  },
  { "title": "Servers Detailed Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Volume Data by container",
   "type": "graph",
   "description": "Volume Data by container",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_writes_total{job=\"$job\"}",
     "legendFormat": "{{image}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "Free space for each partition",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"})"
    }
   ]
  }
 ]
}